/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
- render a sidebar for each doc of that group
- provide next/previous navigation

The sidebars can be generated from the filesystem, or explicitly defined here.

Create as many sidebars as you want.
*/

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: "autogenerated", dirName: "."}],

    // But you can create a sidebar manually
    doc1Sidebar: [
        "intro",
        "install",
        "usage",
        {
            type: "category",
            label: "eMath",
            items: [
                {
                    type: "category",
                    label: "E",
                    items: [
                        "eMath/E/E",
                        "eMath/E/format",
                    ],
                },
                {
                    type: "category",
                    label: "Classes",
                    items: [
                        "eMath/classes/attribute",
                        "eMath/classes/boost",
                        "eMath/classes/currency",
                    ],
                },
            ],
        },
    ],
    tutorialSidebar: [
        "tutorials/tutorials",
        {
            type: "category",
            label: "Coin Game",
            items: [
                "tutorials/coinGame/intro",
                "tutorials/coinGame/setup",
                "tutorials/coinGame/currency",
                "tutorials/coinGame/upgrades",
            ],
        },
    ],
};

module.exports = sidebars;
